spring.application.name=NextMessage
server.port=8080

spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/NextMessage
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

jwt.secret=3fn8vh23nf2u8i3hfg98257623fnh23jubfg872htj23ngfu823ht87
jwt.expiration=360000000

#Need to insert:
#http://localhost:8080/v3/api-docs

#Into search bar in:
#http://localhost:8080/swagger-ui/index.html